### ISSUE TITLE
psremote and finddotnet are completely ignored on the console.

### ISSUE THREAD

**Issue by zufukatana** [REDMED-X/OperatorsKit#1]
psremote and findotnet are added as alias but there is no output after running them. as if the cna is not fetching the bof.
is it the same you ? thanks

**Comment by REDMED-X** [comment]
I pushed a small fix for the aggressor scripts in the case some irregular indentation were causing problems. Also, please make sure  the .o file is in the same directory as the .cna script.

**Comment by zufukatana** [comment]
worked perfectly thanks alot, reloading the client itself solved the problem after reloading the cna of course.
