### ISSUE TITLE
Hidefile does not seem to work for me

### ISSUE THREAD

**Issue by carlnykvist** [REDMED-X/OperatorsKit#2]
Hi,

I'm trying the hidefile BOF but it does not seem to work for me. I tested this as a low-priv user on Microsoft Windows 11 Enterprise N (10.0.22000 N/A Build 22000)

![image](https://user-images.githubusercontent.com/5971228/225897766-41652a44-8dd6-4a18-a785-31bdbc257601.png)

**Comment by REDMED-X** [comment]
Hi,

I can't seem to reproduce your issue on my Windows 11 test client. The thing that stands out to me is that only the hidefile.cna output is shown and not any output from the BOF itself (no error message or success message). Maybe dubbel check that the hidefile.cna script points to correct location on disk were the hidefile.o file is stored. 

For your reference, this is how it should look like:

![results](https://user-images.githubusercontent.com/124559144/226442322-96d9b164-e5ad-4c30-a5cf-8a7d4417139b.png)

**Comment by carlnykvist** [comment]
I get the same message as you, but when listing files in the folder, it still shows the file.

![image](https://user-images.githubusercontent.com/5971228/229104391-76ab38db-81bf-4735-8ded-8f3160271369.png)

**Comment by REDMED-X** [comment]
And visually in the GUI folder on the target system? The `ls` and `dir` commands in CS will also show files that are hidden or are system files. You can also check if the BOF works by using the `dir` command directly from powershell/cmd. This shouldn't list the "hidden" files.

**Comment by carlnykvist** [comment]
Ah I see, my bad. I didn't know that ls & and dir command in CS showed hidden files. Everything works as expected. Thank you for the answer.
